version: "3.9"
services:
  db-mssql:
    container_name: "tasktower-db-mssql"
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=password123
    networks:
      - tasktower-backend
  local-redis:
    container_name: "tasktower-local-redis"
    image: bitnami/redis:6.0.9
    ports:
        - "6379:6379"
    environment:
        - REDIS_PASSWORD=password123
    networks:
      - tasktower-backend
  shared-redis:
    container_name: "tasktower-shared-redis"
    image: bitnami/redis:6.0.9
    ports:
        - "6378:6379"
    environment:
        - REDIS_PASSWORD=password123
    networks:
      - tasktower-backend
#  tasktower-nginx-gateway:
#    container_name: "tasktower-nginx-gateway"
#    build: ../tasktower-nginx-gateway
#    depends_on: 
#      - tasktower-auth-service
#    ports:
#      - "443:443"
#    networks:
#      - tasktower-backend

networks:
  tasktower-backend:
    driver: bridge