version: "3.9"
services:
  db-mssql:
    container_name: "tasktower-db-mssql"
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=P@ssword123
  local-redis:
    container_name: "tasktower-local-redis"
    image: bitnami/redis:6.0.9
    ports:
        - "6379:6379"
    environment:
        - REDIS_PASSWORD=password123
  shared-redis:
    container_name: "tasktower-shared-redis"
    image: bitnami/redis:6.0.9
    ports:
        - "6378:6379"
    environment:
        - REDIS_PASSWORD=password123
  tasktower-nginx-gateway:
    container_name: "tasktower-nginx-gateway"
    build: dockerfiles/NginxGateway
    depends_on:
        - db-mssql
    ports:
      - "443:443"