version: "3.9"
services:
  tasktower-mssql-db:
    container_name: "tasktower-mssql-db"
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssword123
    networks:
      - tasktower
  tasktower-redis:
    container_name: "tasktower-redis"
    image: bitnami/redis:6.0.9
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password123
    networks:
      - tasktower
  tasktower-ui-service:
    container_name: "tasktower-ui-service"
    build: dockerfiles/UIService
    ports:
      - "8081:80"
    networks:
      - tasktower
  tasktower-nginx-gateway:
    container_name: "tasktower-nginx-gateway"
    build: dockerfiles/NginxGateway
    depends_on:
      - tasktower-ui-service
    ports:
      - "8080:443"
    networks:
      - tasktower
networks:
  tasktower:
    driver: bridge