version: "3.9"
services:
  tasktower-mssql-db:
    container_name: "tasktower-mssql-db"
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssword123
    networks:
      - tasktower
  tasktower-redis:
    container_name: "tasktower-redis"
    image: bitnami/redis:6.0.9
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password123
    networks:
      - tasktower
  tasktower-board-service:
    container_name: "tasktower-board-service"
    image: tasktower-boardservice
    ports:
      - "8082:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - Auth__Authority=https://dev-cl8od7hx.us.auth0.com
      - Auth__Audience=OSafhsQn1OiTPAsuh79GZY04O7SaIAoe
      - ConnectionStrings__SQLServerBoardDB=Data Source=tasktower-mssql-db;Server=tasktower-mssql-db;User ID=sa;Password=P@ssword123;Database=board;
    depends_on:
      - tasktower-redis
      - tasktower-mssql-db
    networks:
      - tasktower
  tasktower-ui-service:
    container_name: "tasktower-ui-service"
    image: tasktower-uiservice
    ports:
      - "8081:80"
    networks:
      - tasktower
  tasktower-ocelot-gateway:
    container_name: "tasktower-ocelot-gateway"
    image: tasktower-ocelotapigateway
    depends_on:
      - tasktower-ui-service
      - tasktower-board-service
    ports:
      - "8080:80"
    networks:
      - tasktower
networks:
  tasktower:
    driver: bridge